import Header from '@/components/Header';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Footer from '@/components/Footer';
import AuthProvider from '@/components/providers/AuthProvider';
import QueryProvider from '@/components/providers/QueryProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <QueryProvider>
        <AuthProvider>
          <body className={inter.className + ' ' + 'body'}>
            <Header />
            <main>{children}</main>
            <Footer />
          </body>
        </AuthProvider>
      </QueryProvider>
    </html>
  );
}
